grep -r -l "resolv.conf" 
.git/index
.git/objects/pack/pack-014286024f540eb462e817748eb692051f2b7987.pack
feeds/packages/libs/avahi/files/avahi-daemon.conf
feeds/packages/net/isc-dhcp/files/dhcpd.init
feeds/packages/net/isc-dhcp/files/dhclient-script
feeds/packages/net/unbound/files/unbound.sh
feeds/packages/net/unbound/files/defaults.sh
feeds/packages/net/unbound/files/README.md
feeds/packages/net/unbound/files/unbound.uci
feeds/packages/net/dnsforwarder/files/etc/init.d/dnsforwarder
feeds/packages/net/stubby/files/README.md
feeds/packages/net/libreswan/files/etc/hotplug.d/libreswan/00-default
feeds/luci/modules/luci-base/po/ja/base.po
feeds/luci/modules/luci-base/po/ca/base.po
feeds/luci/modules/luci-base/po/hu/base.po
feeds/luci/modules/luci-base/po/fa/base.po
feeds/luci/modules/luci-base/po/ar/base.po
feeds/luci/modules/luci-base/po/ko/base.po
feeds/luci/modules/luci-base/po/vi/base.po
feeds/luci/modules/luci-base/po/ms/base.po
feeds/luci/modules/luci-base/po/id/base.po
feeds/luci/modules/luci-base/po/mr/base.po
feeds/luci/modules/luci-base/po/sv/base.po
feeds/luci/modules/luci-base/po/nl/base.po
feeds/luci/modules/luci-base/po/ast/base.po
feeds/luci/modules/luci-base/po/pl/base.po
feeds/luci/modules/luci-base/po/yua/base.po
feeds/luci/modules/luci-base/po/nb_NO/base.po
feeds/luci/modules/luci-base/po/hi/base.po
feeds/luci/modules/luci-base/po/ml/base.po
feeds/luci/modules/luci-base/po/da/base.po
feeds/luci/modules/luci-base/po/zh_Hant/base.po
feeds/luci/modules/luci-base/po/uk/base.po
feeds/luci/modules/luci-base/po/ro/base.po
feeds/luci/modules/luci-base/po/lt/base.po
feeds/luci/modules/luci-base/po/bg/base.po
feeds/luci/modules/luci-base/po/ga/base.po
feeds/luci/modules/luci-base/po/bn_BD/base.po
feeds/luci/modules/luci-base/po/pt_BR/base.po
feeds/luci/modules/luci-base/po/templates/base.pot
feeds/luci/modules/luci-base/po/el/base.po
feeds/luci/modules/luci-base/po/zh_Hans/base.po
feeds/luci/modules/luci-base/po/de/base.po
feeds/luci/modules/luci-base/po/fr/base.po
feeds/luci/modules/luci-base/po/he/base.po
feeds/luci/modules/luci-base/po/sk/base.po
feeds/luci/modules/luci-base/po/fi/base.po
feeds/luci/modules/luci-base/po/it/base.po
feeds/luci/modules/luci-base/po/fil/base.po
feeds/luci/modules/luci-base/po/ru/base.po
feeds/luci/modules/luci-base/po/pt/base.po
feeds/luci/modules/luci-base/po/ur/base.po
feeds/luci/modules/luci-base/po/es/base.po
feeds/luci/modules/luci-base/po/tr/base.po
feeds/luci/modules/luci-base/po/cs/base.po
feeds/luci/modules/luci-mod-network/htdocs/luci-static/resources/view/network/dhcp.js
feeds/luci/modules/luci-mod-network/htdocs/luci-static/resources/view/network/interfaces.js
feeds/luci/applications/luci-app-olsr/htdocs/luci-static/resources/view/olsr/frontend/olsrdplugins.js
feeds/luci/applications/luci-app-olsr/htdocs/luci-static/resources/view/olsr/frontend/olsrdplugins6.js
feeds/luci/applications/luci-app-openclash/root/etc/init.d/openclash
feeds/luci/applications/luci-app-openclash/root/usr/share/openclash/openclash_debug.sh
feeds/luci/applications/luci-app-unbound/luasrc/model/cbi/unbound/zone-details.lua
feeds/luci/applications/luci-app-unbound/luasrc/model/cbi/unbound/zones.lua
feeds/luci/applications/luci-app-unbound/po/ja/unbound.po
feeds/luci/applications/luci-app-unbound/po/ca/unbound.po
feeds/luci/applications/luci-app-unbound/po/hu/unbound.po
feeds/luci/applications/luci-app-unbound/po/ar/unbound.po
feeds/luci/applications/luci-app-unbound/po/ko/unbound.po
feeds/luci/applications/luci-app-unbound/po/vi/unbound.po
feeds/luci/applications/luci-app-unbound/po/ms/unbound.po
feeds/luci/applications/luci-app-unbound/po/mr/unbound.po
feeds/luci/applications/luci-app-unbound/po/sv/unbound.po
feeds/luci/applications/luci-app-unbound/po/nl/unbound.po
feeds/luci/applications/luci-app-unbound/po/pl/unbound.po
feeds/luci/applications/luci-app-unbound/po/nb_NO/unbound.po
feeds/luci/applications/luci-app-unbound/po/hi/unbound.po
feeds/luci/applications/luci-app-unbound/po/da/unbound.po
feeds/luci/applications/luci-app-unbound/po/zh_Hant/unbound.po
feeds/luci/applications/luci-app-unbound/po/uk/unbound.po
feeds/luci/applications/luci-app-unbound/po/ro/unbound.po
feeds/luci/applications/luci-app-unbound/po/lt/unbound.po
feeds/luci/applications/luci-app-unbound/po/bg/unbound.po
feeds/luci/applications/luci-app-unbound/po/ga/unbound.po
feeds/luci/applications/luci-app-unbound/po/bn_BD/unbound.po
feeds/luci/applications/luci-app-unbound/po/pt_BR/unbound.po
feeds/luci/applications/luci-app-unbound/po/templates/unbound.pot
feeds/luci/applications/luci-app-unbound/po/el/unbound.po
feeds/luci/applications/luci-app-unbound/po/zh_Hans/unbound.po
feeds/luci/applications/luci-app-unbound/po/de/unbound.po
feeds/luci/applications/luci-app-unbound/po/fr/unbound.po
feeds/luci/applications/luci-app-unbound/po/he/unbound.po
feeds/luci/applications/luci-app-unbound/po/sk/unbound.po
feeds/luci/applications/luci-app-unbound/po/fi/unbound.po
feeds/luci/applications/luci-app-unbound/po/it/unbound.po
feeds/luci/applications/luci-app-unbound/po/ru/unbound.po
feeds/luci/applications/luci-app-unbound/po/pt/unbound.po
feeds/luci/applications/luci-app-unbound/po/es/unbound.po
feeds/luci/applications/luci-app-unbound/po/tr/unbound.po
feeds/luci/applications/luci-app-unbound/po/cs/unbound.po
feeds/luci/applications/luci-app-passwall/root/usr/share/passwall/helper_dnsmasq.lua
feeds/luci/applications/luci-app-passwall/root/usr/share/passwall/app.sh
feeds/luci/libs/rpcd-mod-rrdns/src/rrdns.c
package/network/services/ipset-dns/files/ipset-dns.config
package/network/services/ppp/Makefile
package/network/services/dnsmasq/Makefile
package/network/services/dnsmasq/files/dnsmasq.init
package/network/services/dnsmasq/files/50-dnsmasq-migrate-resolv-conf-auto.sh
package/network/services/dnsmasq/files/dhcp.conf
package/base-files/Makefile
package/base-files/files/etc/init.d/boot
package/base-files/files/lib/upgrade/stage2
